#!/usr/bin/python3

password_address = 0xc8(%rbp) # Replace this with the actual memory address
password_length = 20

# Read the password from memory
with open('101-crackme_password', 'wb') as f:
    f.write(bytes([password_address + i for i in range(password_length)]))

